### ISSUE TITLE
toolkit compiling error

### ISSUE THREAD

**Issue by nachitoys** [LxMLS/lxmls-toolkit#49]
Hi all..

I recently tried to compile dempendecies for my LxMLS toolkit. I had the following problems. Thank you in advance.

```
~$ git clone https://github.com/LxMLS/lxmls-toolkit.git
Cloning into 'lxmls-toolkit'...
remote: Counting objects: 1800, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 1800 (delta 6), reused 0 (delta 0), pack-reused 1784
Receiving objects: 100% (1800/1800), 22.31 MiB | 57.00 KiB/s, done.
Resolving deltas: 100% (1091/1091), done.
Checking connectivity... done.
~$ cd lxmls-toolkit
~/lxmls-toolkit$ pip install -r pip-requirements.txt
Downloading/unpacking configparser==3.2.0r3 (from -r pip-requirements.txt (line 1))
  Downloading configparser-3.2.0r3.tar.gz
  Running setup.py (path:/tmp/pip_build_iarroyof/configparser/setup.py) egg_info for package configparser
    
Downloading/unpacking pyyaml (from -r pip-requirements.txt (line 2))
  Downloading PyYAML-3.11.tar.gz (248kB): 248kB downloaded
  Running setup.py (path:/tmp/pip_build_iarroyof/pyyaml/setup.py) egg_info for package pyyaml
    
Downloading/unpacking nltk (from -r pip-requirements.txt (line 3))
  Downloading nltk-3.0.3.tar.gz (1.0MB): 1.0MB downloaded
  Running setup.py (path:/tmp/pip_build_iarroyof/nltk/setup.py) egg_info for package nltk
    
    warning: no files found matching 'Makefile' under directory '*.txt'
    warning: no previously-included files matching '*~' found anywhere in distribution
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/lib/python2.7/dist-packages (from -r pip-requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): scipy in /usr/lib/python2.7/dist-packages (from -r pip-requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): matplotlib in /usr/lib/pymodules/python2.7 (from -r pip-requirements.txt (line 6))
Downloading/unpacking mrjob (from -r pip-requirements.txt (line 7))
  Downloading mrjob-0.4.4.tar.gz (186kB): 186kB downloaded
  Running setup.py (path:/tmp/pip_build_iarroyof/mrjob/setup.py) egg_info for package mrjob
    
    no previously-included directories found matching 'docs'
    warning: no files found matching '*.sh' under directory 'bootstrap'
Downloading/unpacking theano (from -r pip-requirements.txt (line 8))
  Downloading Theano-0.7.0.tar.gz (2.0MB): 2.0MB downloaded
  Running setup.py (path:/tmp/pip_build_iarroyof/theano/setup.py) egg_info for package theano
    
    warning: manifest_maker: MANIFEST.in, line 8: 'recursive-include' expects <dir> <pattern1> <pattern2> ...
    
Downloading/unpacking ordereddict (from configparser==3.2.0r3->-r pip-requirements.txt (line 1))
  Downloading ordereddict-1.1.tar.gz
  Running setup.py (path:/tmp/pip_build_iarroyof/ordereddict/setup.py) egg_info for package ordereddict
    
Downloading/unpacking unittest2 (from configparser==3.2.0r3->-r pip-requirements.txt (line 1))
  Downloading unittest2-1.1.0-py2.py3-none-any.whl (96kB): 96kB downloaded
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/lib/python2.7/dist-packages (from matplotlib->-r pip-requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): tornado in /usr/lib/python2.7/dist-packages (from matplotlib->-r pip-requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): pyparsing>=1.5.6 in /usr/lib/python2.7/dist-packages (from matplotlib->-r pip-requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): nose in /usr/lib/python2.7/dist-packages (from matplotlib->-r pip-requirements.txt (line 6))
Downloading/unpacking boto>=2.2.0 (from mrjob->-r pip-requirements.txt (line 7))
  Downloading boto-2.38.0-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Downloading/unpacking filechunkio (from mrjob->-r pip-requirements.txt (line 7))
  Downloading filechunkio-1.6.tar.gz
  Running setup.py (path:/tmp/pip_build_iarroyof/filechunkio/setup.py) egg_info for package filechunkio
    
Requirement already satisfied (use --upgrade to upgrade): simplejson>=2.0.9 in /usr/lib/python2.7/dist-packages (from mrjob->-r pip-requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): six>=1.4 in /usr/lib/python2.7/dist-packages (from unittest2->configparser==3.2.0r3->-r pip-requirements.txt (line 1))
Downloading/unpacking traceback2 (from unittest2->configparser==3.2.0r3->-r pip-requirements.txt (line 1))
  Downloading traceback2-1.4.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python2.7 (from unittest2->configparser==3.2.0r3->-r pip-requirements.txt (line 1))
Downloading/unpacking linecache2 (from traceback2->unittest2->configparser==3.2.0r3->-r pip-requirements.txt (line 1))
  Downloading linecache2-1.0.0-py2.py3-none-any.whl
Installing collected packages: configparser, pyyaml, nltk, mrjob, theano, ordereddict, unittest2, boto, filechunkio, traceback2, linecache2
  Running setup.py install for configparser
    error: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/configparser_helpers.py'
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_iarroyof/configparser/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-PSZTAo-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

copying configparser.py -> build/lib.linux-x86_64-2.7

copying configparser_helpers.py -> build/lib.linux-x86_64-2.7

running install_lib

copying build/lib.linux-x86_64-2.7/configparser_helpers.py -> /usr/local/lib/python2.7/dist-packages

error: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/configparser_helpers.py'

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_iarroyof/configparser/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-PSZTAo-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_iarroyof/configparser
Storing debug log for failure in /home/iarroyof/.pip/pip.log
```
After that, I suppose it is needed su privileges, but it didn't work: 
```
~/lxmls-toolkit$ sudo pip install -r pip-requirements.txt
[sudo] password for iarroyof: 
Downloading/unpacking configparser==3.2.0r3 (from -r pip-requirements.txt (line 1))
  Downloading configparser-3.2.0r3.tar.gz
  Running setup.py (path:/tmp/pip_build_root/configparser/setup.py) egg_info for package configparser
    
Downloading/unpacking pyyaml (from -r pip-requirements.txt (line 2))
  Downloading PyYAML-3.11.tar.gz (248kB): 248kB downloaded
  Running setup.py (path:/tmp/pip_build_root/pyyaml/setup.py) egg_info for package pyyaml
    
Downloading/unpacking nltk (from -r pip-requirements.txt (line 3))
  Downloading nltk-3.0.3.tar.gz (1.0MB): 1.0MB downloaded
  Running setup.py (path:/tmp/pip_build_root/nltk/setup.py) egg_info for package nltk
    
    warning: no files found matching 'Makefile' under directory '*.txt'
    warning: no previously-included files matching '*~' found anywhere in distribution
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/lib/python2.7/dist-packages (from -r pip-requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): scipy in /usr/lib/python2.7/dist-packages (from -r pip-requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): matplotlib in /usr/lib/pymodules/python2.7 (from -r pip-requirements.txt (line 6))
Downloading/unpacking mrjob (from -r pip-requirements.txt (line 7))
  Downloading mrjob-0.4.4.tar.gz (186kB): 186kB downloaded
  Running setup.py (path:/tmp/pip_build_root/mrjob/setup.py) egg_info for package mrjob
    
    no previously-included directories found matching 'docs'
    warning: no files found matching '*.sh' under directory 'bootstrap'
Downloading/unpacking theano (from -r pip-requirements.txt (line 8))
  Downloading Theano-0.7.0.tar.gz (2.0MB): 1.3MB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1197, in prepare_files
    do_download,
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1375, in unpack_url
    self.session,
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 572, in unpack_http_url
    download_hash = _download_url(resp, link, temp_location)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 433, in _download_url
    for chunk in resp_read(4096):
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 421, in resp_read
    chunk_size, decode_content=False):
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 225, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 174, in read
    data = self._fp.read(amt)
  File "/usr/lib/python2.7/httplib.py", line 567, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
SSLError: The read operation timed out

Storing debug log for failure in /home/iarroyof/.pip/pip.log
~/lxmls-toolkit$ 
```
Any help will be very appreciated.

**Comment by ramon-astudillo** [comment]
Hi nachitoys,

you should need sudo. The error appearing the second time seems to be a time-out error. Did you try to repeat the install?.

If you are a LxMLS 2015 participant, feel free to use the lxmls-2015-participants@googlegroups.com list to share your problems about tool installation.

**Comment by nachitoys** [comment]
@ramon-astudillo  Thank you very much for answer. As you suggested I did try again. There is a different log:
```
~$ cd lxmls-toolkit
~/lxmls-toolkit$ sudo pip install -r pip-requirements.txt
[sudo] password for iarroyof: 
Downloading/unpacking configparser==3.2.0r3 (from -r pip-requirements.txt (line 1))
  Downloading configparser-3.2.0r3.tar.gz
  Running setup.py (path:/tmp/pip_build_root/configparser/setup.py) egg_info for package configparser
    
Downloading/unpacking pyyaml (from -r pip-requirements.txt (line 2))
  Downloading PyYAML-3.11.tar.gz (248kB): 248kB downloaded
  Running setup.py (path:/tmp/pip_build_root/pyyaml/setup.py) egg_info for package pyyaml
    
Downloading/unpacking nltk (from -r pip-requirements.txt (line 3))
  Downloading nltk-3.0.3.tar.gz (1.0MB): 1.0MB downloaded
  Running setup.py (path:/tmp/pip_build_root/nltk/setup.py) egg_info for package nltk
    
    warning: no files found matching 'Makefile' under directory '*.txt'
    warning: no previously-included files matching '*~' found anywhere in distribution
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/lib/python2.7/dist-packages (from -r pip-requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): scipy in /usr/lib/python2.7/dist-packages (from -r pip-requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): matplotlib in /usr/lib/pymodules/python2.7 (from -r pip-requirements.txt (line 6))
Downloading/unpacking mrjob (from -r pip-requirements.txt (line 7))
  Downloading mrjob-0.4.4.tar.gz (186kB): 186kB downloaded
  Running setup.py (path:/tmp/pip_build_root/mrjob/setup.py) egg_info for package mrjob
    
    no previously-included directories found matching 'docs'
    warning: no files found matching '*.sh' under directory 'bootstrap'
Downloading/unpacking theano (from -r pip-requirements.txt (line 8))
  Downloading Theano-0.7.0.tar.gz (2.0MB): 2.0MB downloaded
  Running setup.py (path:/tmp/pip_build_root/theano/setup.py) egg_info for package theano
    
    warning: manifest_maker: MANIFEST.in, line 8: 'recursive-include' expects <dir> <pattern1> <pattern2> ...
    
Downloading/unpacking ordereddict (from configparser==3.2.0r3->-r pip-requirements.txt (line 1))
  Downloading ordereddict-1.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/ordereddict/setup.py) egg_info for package ordereddict
    
Downloading/unpacking unittest2 (from configparser==3.2.0r3->-r pip-requirements.txt (line 1))
  Downloading unittest2-1.1.0-py2.py3-none-any.whl (96kB): 96kB downloaded
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/lib/python2.7/dist-packages (from matplotlib->-r pip-requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): tornado in /usr/lib/python2.7/dist-packages (from matplotlib->-r pip-requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): pyparsing>=1.5.6 in /usr/lib/python2.7/dist-packages (from matplotlib->-r pip-requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): nose in /usr/lib/python2.7/dist-packages (from matplotlib->-r pip-requirements.txt (line 6))
Downloading/unpacking boto>=2.2.0 (from mrjob->-r pip-requirements.txt (line 7))
  Downloading boto-2.38.0-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Downloading/unpacking filechunkio (from mrjob->-r pip-requirements.txt (line 7))
  Downloading filechunkio-1.6.tar.gz
  Running setup.py (path:/tmp/pip_build_root/filechunkio/setup.py) egg_info for package filechunkio
    
Requirement already satisfied (use --upgrade to upgrade): simplejson>=2.0.9 in /usr/lib/python2.7/dist-packages (from mrjob->-r pip-requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): six>=1.4 in /usr/lib/python2.7/dist-packages (from unittest2->configparser==3.2.0r3->-r pip-requirements.txt (line 1))
Downloading/unpacking traceback2 (from unittest2->configparser==3.2.0r3->-r pip-requirements.txt (line 1))
  Downloading traceback2-1.4.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python2.7 (from unittest2->configparser==3.2.0r3->-r pip-requirements.txt (line 1))
Downloading/unpacking linecache2 (from traceback2->unittest2->configparser==3.2.0r3->-r pip-requirements.txt (line 1))
  Downloading linecache2-1.0.0-py2.py3-none-any.whl
Installing collected packages: configparser, pyyaml, nltk, mrjob, theano, ordereddict, unittest2, boto, filechunkio, traceback2, linecache2
  Running setup.py install for configparser
    
  Running setup.py install for pyyaml
    checking if libyaml is compilable
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/check_libyaml.c -o build/temp.linux-x86_64-2.7/check_libyaml.o
    build/temp.linux-x86_64-2.7/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
     #include <yaml.h>
                      ^
    compilation terminated.
    
    libyaml is not found or a compiler error: forcing --without-libyaml
    (if libyaml is installed correctly, you may need to
     specify the option --include-dirs or uncomment and
     modify the parameter include_dirs in setup.cfg)
    
  Running setup.py install for nltk
    
    warning: no files found matching 'Makefile' under directory '*.txt'
    warning: no previously-included files matching '*~' found anywhere in distribution
  Running setup.py install for mrjob
    changing mode of build/scripts-2.7/mrjob from 644 to 755
    
    no previously-included directories found matching 'docs'
    warning: no files found matching '*.sh' under directory 'bootstrap'
    changing mode of /usr/local/bin/mrjob to 755
  Running setup.py install for theano
    changing mode of build/scripts-2.7/theano-cache from 644 to 755
    changing mode of build/scripts-2.7/theano-nose from 644 to 755
    changing mode of build/scripts-2.7/theano-test from 644 to 755
    
    warning: manifest_maker: MANIFEST.in, line 8: 'recursive-include' expects <dir> <pattern1> <pattern2> ...
    
    changing mode of /usr/local/bin/theano-cache to 755
    changing mode of /usr/local/bin/theano-nose to 755
    changing mode of /usr/local/bin/theano-test to 755
  Running setup.py install for ordereddict
    
  Running setup.py install for filechunkio
    
Compiling /tmp/pip_build_root/linecache2/linecache2/tests/inspect_fodder2.py ...
  File "/tmp/pip_build_root/linecache2/linecache2/tests/inspect_fodder2.py", line 102
    def keyworded(*arg1, arg2=1):
                            ^
SyntaxError: invalid syntax

Successfully installed configparser pyyaml nltk mrjob theano ordereddict unittest2 boto filechunkio traceback2 linecache2
Cleaning up...
~/lxmls-toolkit$_
```
You think the "syntax error" is not problematic? my latter intent is really successful?

PD. Indeed Im a MLS participant. I will post the conversation in the group also.

**Comment by ramon-astudillo** [comment]
Nao, eles estao instalado so oa modulos.



—
